language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls -v